package com.neicake.cafeapp.util;

public enum PurchaseError{
	INVALID_PURCHASE_AMOUNT,
	INVALID_CUSTOMER,
	INVALID_PRODUCT,
	INVALID_COUPON,
	INVALID_PRODUCT_DISCOUNT,
	INVALID_DATE,
	MISSING_PARAMETER

}